spring:
  datasource:
    url: jdbc:h2:file:~/.h2/springboot-learning
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console #控制台查看数据库的路径  localhost:8080/h2-console
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true