server:
  port: 8081
# Spring Boot Admin 监控服务器端地址
spring:
  application:
    name: spring-boot-admin-client
  boot:
    admin:
      client:
        url: http://192.168.61.137:9091
        instance:
          service-host-type: ip
          service-url: http://10.7.8.84:8081
management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  file:
    path: E:\\work\\log