server:
  port: 8081
  servlet-path: /Velocity
# 配置velocity
  velocity :
    cache: false
    charset: UTF-8
    check-template-location: false
    content-type: text/html
    enabled: true
    prefix: /templates/
    suffix: .vm


