logging:
  level:
    druid:
      sql:
        Statement: debug
spring:
  datasource:
    druid:
      filter:
        slf4j:
          enabled: true
          statementCloseAfterLogEnabled: false
          statementCreateAfterLogEnabled: false
          statementExecutableSqlLogEnable: true
          statementExecuteAfterLogEnabled: false
          statementExecuteBatchAfterLogEnabled: false
          statementExecuteQueryAfterLogEnabled: false
          statementExecuteUpdateAfterLogEnabled: false
          statementLogEnabled: true
          statementParameterSetLogEnabled: false
          statementPrepareAfterLogEnabled: false
          statementPrepareCallAfterLogEnabled: false