server:
  port: 9091
spring:
  boot:
    admin:
      notify:
        mail:
          from: 1447660461@qq.com
          to: 1447660461@qq.com
  mail:
    host: smtp.qq.com
    password: lpxcqaucrfdeifhh
    username: 1447660461@qq.com
  security:
    user:
      name: java666
      password: java666
      roles: SBA_ADMIN