server:
  port: 8080
spring:
  application:
    name: prometheus-test
management:
  endpoints:
    promethus:
      enable: true
    web:
      exposure:
#        exclude: "prometheus"
        include: '*'
  metrics:
    tags:
      application: ${spring.application.name}
  endpoint:
      health:
        show-details: always

