spring:
  datasource:
    url: jdbc:mysql://124.71.38.83:3306/test?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: tt19950826TT.
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  type-enums-package: org.example.enums


