spring:
  profiles:
    active:
    - pro
# 配置微服务的地址
com:
  didispace:
    database-platform: sql
    foo: bar
    post:
      - Why Spring Boot
      - Why Spring Cloud
    posts:
      - content: It is perfect!
        title: Why Spring Boot
      - content: It is perfect too!
        title: Why Spring Cloud


url:
  # 订单微服务的地址
  orderUrl: http://localhost:8002
  # 用户微服务的地址
  userUrl: http://localhost:8003
  # 购物车微服务的地址
  shoppingUrl: http://localhost:8004