spring:
  data:
    mongodb:
      uri: mongodb://root:123456@localhost:27017,localhost:27018,lcoalhost:27017
      database: springboot-learning
      authentication-database: admin
      transactionEnabled: true
      #field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy
      #驼峰转下划线
      property-naming-strategy: SNAKE_CASE